export const ADICIONA_PROJETO = 'ADICIONA_PROJETO'
export const ALTERA_PROJETO = 'ALTERA_PROJETO'
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO'

export const ADICIONAR_TAREFA = 'ADICIONAR_TAREFA'
export const ALTERAR_TAREFA = 'ALTERAR_TAREFA'
export const EXCLUIR_TAREFA = 'EXCLUIR_TAREFA'

export const NOTIFICAR = 'NOTIFICAR'